apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
     serving.kserve.io/s3-endpoint: mlflow-minio-service.mlflow.svc.cluster.local:9000
     serving.kserve.io/s3-usehttps: "0"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
secrets:
- name: mysecret
