apiVersion: v1
kind: Endpoints
metadata:
   name: remote-ray-1 
subsets:
  - addresses:
    - ip: '(your_vm_private_ip)'
    ports: 
      - port: (dashboard_port)
---
apiVersion: v1
kind: Service
metadata:
   name: remote-ray-1 
   annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '0'
spec:
   type: ClusterIP
   ports:
   - protocol: TCP
     port: (dashboard_port)
     targetPort: (dashboard_port)