apiVersion: v1
kind: Service
metadata:
  name: celery-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '6502'
spec:
  selector: 
    app: celery-server
  ports:
    - port: 6502
      targetPort: 6502