apiVersion: v1
kind: ServiceAccount
metadata:
  name: celery-sa
  namespace: forwarder
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: celery-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: celery-binding
subjects:
  - kind: ServiceAccount
    name: celery-sa
    namespace: forwarder
roleRef:
  kind: ClusterRole
  name: celery-role
  apiGroup: rbac.authorization.k8s.io