apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio-server 
  ports:
  - port: 9100
    targetPort: 9000 
    protocol: TCP
    name: server
  - port: 9101
    targetPort: 9001
    protocol: TCP
    name: console