apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-server
  labels:
    app: minio-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-server
  template:
    metadata:
      labels:
        app: minio-server
    spec:
      nodeSelector: 
        "kubernetes.io/os": linux
      containers:
      - name: minio-server
        image: minio/minio:RELEASE.2025-01-20T14-49-07Z
        imagePullPolicy: Always
        command: [ "/bin/bash" ]
        args: [ "-c", "mkdir -p /data && minio server --address :9000 --console-address :9001 /data" ]
        ports:
          - containerPort: 9000
          - containerPort: 9001 
        volumeMounts:
        - name: minio-pvc
          mountPath: '/data'
        env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: storage-configmap
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: MINIO_ROOT_PASSWORD
      volumes:
      - name: minio-pvc
        persistentVolumeClaim:
          claimName: minio-pvc