apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  labels:
    app: mongodb-server
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-log-pvc
  labels:
    app: mongodb-server
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 5Gi