apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  labels:
    app: neo4j-server
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-log-pvc
  labels:
    app: neo4j-server
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 5Gi