apiVersion: v1
kind: Endpoints
metadata:
   name: ray-local-head-1 
subsets:
  - addresses:
    - ip: '192.168.1.224'
    ports: 
      - port: 9380
---
apiVersion: v1
kind: Service
metadata:
   name: ray-local-head-1 
   annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '0'
spec:
   type: ClusterIP
   ports:
   - protocol: TCP
     port: 9380
     targetPort: 9380