apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-server 
spec:
  selector:
    app: postgres-server
  ports:
    - port: 5532
      targetPort: 5432
      name: postgres 