apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  labels:
    app: mongo-server
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-log-pvc
  labels:
    app: mongo-server
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
      storage: 5Gi